.F
======================================================================
FAIL: testsnap (testCLI.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testCLI.py", line 54, in testsnap
    self.isconf('-m "testing snap" lock')
  File "testCLI.py", line 29, in isconf
    self.failUnless(self.quiet((realrc, stdin, stdout, stderr)))
  File "testCLI.py", line 39, in quiet
    self.fail("not quiet")
  File "/usr/lib/python2.2/unittest.py", line 254, in fail
    raise self.failureException, msg
AssertionError: not quiet

----------------------------------------------------------------------
Ran 2 tests in 18.701s

FAILED (failures=1)
python2.2 ./coverage.py -x ../bin/isconf -c simple.conf start
python2.2 ./coverage.py -x ../bin/isconf -c simple.conf -q 
python2.2 ./coverage.py -x ../bin/isconf -c simple.conf -q -m "testing snap" lock
Traceback (most recent call last):
  File "./coverage.py", line 540, in ?
    the_coverage.command_line()
  File "./coverage.py", line 183, in command_line
    execfile(sys.argv[0], __main__.__dict__)
  File "../bin/isconf", line 7, in ?
    main.main()
  File "/home/stevegt/svn/isconf/trunk/lib/python/isconf/Main.py", line 93, in main
    rc = self.client()
  File "/home/stevegt/svn/isconf/trunk/lib/python/isconf/Main.py", line 101, in client
    transport = UNIXClientSocket(path = ctl)
  File "/home/stevegt/svn/isconf/trunk/lib/python/isconf/Socket.py", line 174, in __init__
    self.sock.connect(self.ctl)
socket.error: (111, 'Connection refused')

